### ISSUE TITLE
Lots of Passive talents showing trait AbilityLinks

### ISSUE THREAD

**Issue by MGatner** [koliva8245/HeroesDataParser#30]
Worked with @stuaroo on getting the 3.0 changes into heroes-talents. He made a pretty comprehensive list of talents that are showing up with Trait links even though they are type Passive. https://github.com/heroespatchnotes/heroes-talents/pull/38#issuecomment-450634140

**Comment by koliva8245** [comment]
All is intended. So the abilityTalentLinkIds are supposed to match the ingame ability tooltip expanders.  When you hover over an ability and it shows the talent names in yellow text, that's what the abilityTalentLinkIds are supposed to match.

> Active and Passive have no abilityLinks - Yes, expected. Abilities are only base kit (plus ult) so talents that stand as their own abilities (like Varian Banner, Garrosh Body Check) won't ever be linked. Some passive talents should have links (e.g. ZaryaDefensiveShielding)

Talents are supposed to be linked, I fixed with https://github.com/koliva8245/HeroesDataParser/commit/85c2b38a100c9b1a9f906ea8e87cc7d5a3645ec0.
